Activity
uofu-emb/Lab3_BrittneyCristian pull request #1
Opened 2023-10-23 20:09 UTC by ctapiero

merging with main

2023-10-30 22:14 UTC, willgraham345 requested changes
Hey guys! Just a couple of things that I think you'll need to get this thing passed off. Overall I think you did a great job, just want to make sure you don't have any issues when you submit this to Ashton :)

2023-10-30 22:14 UTC, willgraham345 commented on .vscode/c_cpp_properties.json
I'd suggest editing your .gitignore to ignore everything from the .vscode file. This thing will change on every computer, and its usually easiest to ignore everything changing from machine to machine.

2023-10-30 22:14 UTC, willgraham345 commented on .vscode/c_cpp_properties.json
I think it would also be helpful to write a README.md explaining how your repository functions, and where it's passing the tests. It's hard for me to determine if your repository has passed the requisite tests for the assignment without github actions setup or the README.

2023-10-30 23:10 UTC, charming21 commented on .vscode/c_cpp_properties.json
Hi Will, thanks for the feedback.

We updated our gitignore and we also removed the vscode directory as well to keep our repository clean.

2023-10-30 23:40 UTC, charming21 commented on .vscode/c_cpp_properties.json
We created a readme and it list which tests we passed as well as what we did for each activity.

2023-11-01 19:42 UTC, willgraham345 approved these changes

2023-11-01 19:42 UTC, willgraham345 commented on README.md
That's the greatest readme I've ever seen in my life, and I'm ABSOLUTELY going to try and copy it. Selfishly, I'm so happy I said something because this is amazing. Unreal job, I have no idea where you found that.

2023-11-29 22:35 UTC, willgraham345 commented
Oops! Thought I'd already passed this off.

2023-11-29 22:38 UTC, willgraham345 commented
d

2023-11-29 22:39 UTC, willgraham345 commented
Accidentally closed the PR. Passing everything.

2023-11-29 22:42 UTC, Misael812 approved these changes
Everything looks good on my end, good looking README. Good job

2023-11-29 22:44 UTC, merged